{
 "title": "SmartBuilding",
 "time": { "from": "2022-07-06T22:00:00.000Z", "to": "2022-08-07T21:59:59.000Z" },
 "panels": [
  {
   "title": "Battery Charge Percent",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  avg(BatteryCharge) AS \"BatteryCharge\"\nFROM battery\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Solar Panel Efficiency",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  max(Pannelsefficiency) AS \"Pannelsefficiency\"\nFROM solar\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  max(Consumption) AS \"Consumption\"\nFROM electricMeter\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  { "title": "Active Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 } },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Battery Charge Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  avg(BatteryCharge) AS \"BatteryCharge\"\nFROM battery\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amph" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  max(BatteryPower)\nFROM battery\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
    }
   ]
  },
  {
   "title": "Energy Generation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Solar Panel Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  max(PannelsPower) AS \"Pannelsefficiency\"\nFROM solar\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
      }
     ]
    },
    {
     "title": "Solar Panel Efficiency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  max(Pannelsefficiency) AS \"Pannelsefficiency\"\nFROM solar\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
      }
     ]
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Energy Consumption",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  max(Consumption) AS \"Consumption\"\nFROM electricMeter\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Room-1 Temperature",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  sensor AS metric,\n  temperature\nFROM sensordth11\nWHERE\n  $__timeFilter(timestamp)\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "Room-1 Temperature",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 5, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval),\n  sensor AS metric,\n  avg(temperature) AS \"temperature\"\nFROM sensordth11\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval)"
      }
     ]
    }
   ]
  }
 ]
}